name: Build and deploy
on:
  push: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: aarch64
            BASEIMAGE: "quay.io/pypa/manylinux_2_28_aarch64@sha256:d6031c425606be1a43da89e4868ad0deada48ac6fe05e3a027b8fa95e4c007f3"
          - arch: x86_64
            BASEIMAGE: "quay.io/pypa/manylinux_2_28_x86_64@sha256:078fda423323b8483cb8320ac6a0b7c3933d6c332e53225d077ff3186b3ce07e"
    steps:
      - uses: actions/checkout@v4
      - name: docker qemu multi-arch
        if: matrix.arch != 'x86_64'
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset --persistent yes
      - name: build image
        run: |
          docker build \
            --tag "${GITHUB_REPOSITORY}-${{ matrix.arch }}:${GITHUB_SHA}" \
            --build-arg "BASEIMAGE=${{ matrix.BASEIMAGE }}" \
            .
      - name: push image
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${GITHUB_ACTOR}" --password-stdin
          docker tag \
            "${GITHUB_REPOSITORY}-${{ matrix.arch }}:${GITHUB_SHA}" \
            "ghcr.io/${GITHUB_REPOSITORY}-${{ matrix.arch }}:${GITHUB_REF/#refs\/tags\//}"
          docker push "ghcr.io/${GITHUB_REPOSITORY}-${{ matrix.arch }}:${GITHUB_REF/#refs\/tags\//}"
