name: Build and deploy
on:
  push: {}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        include:
          - arch: x86_64
            BASEIMAGE: "quay.io/pypa/manylinux2014_x86_64@sha256:4838a9a802d800eefea3cb0bc30c287ab4a333f2b072748d4f72a3d9c8e5aa96"
            APPIMAGETOOL_URL: "https://github.com/AppImage/AppImageKit/releases/download/12/appimagetool-x86_64.AppImage"
            APPIMAGETOOL_SHA256: d918b4df547b388ef253f3c9e7f6529ca81a885395c31f619d9aaf7030499a13
          - arch: i686
            BASEIMAGE: "quay.io/pypa/manylinux2014_i686@sha256:78d635c755df7f9e970f180720900081af33f00833a4748a08d6f7b6e6716b73"
            APPIMAGETOOL_URL: "https://github.com/AppImage/AppImageKit/releases/download/12/appimagetool-i686.AppImage"
            APPIMAGETOOL_SHA256: 3af6839ab6d236cd62ace9fbc2f86487f0bf104f521d82da6dea4dab8d3ce4ca
          - arch: aarch64
            BASEIMAGE: "quay.io/pypa/manylinux2014_aarch64@sha256:a3904cc784da69539c60b5dbd4b2303113a31f7a819b510709d7c74ae0bc550f"
            APPIMAGETOOL_URL: "https://github.com/AppImage/AppImageKit/releases/download/12/appimagetool-aarch64.AppImage"
            APPIMAGETOOL_SHA256: c9d058310a4e04b9fbbd81340fff2b5fb44943a630b31881e321719f271bd41a
    steps:
      - uses: actions/checkout@v2
      - name: docker qemu multi-arch
        if: matrix.arch != 'x86_64'
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset --persistent yes
      - name: build image
        run: |
          docker build \
            --tag "${GITHUB_REPOSITORY}-${{ matrix.arch }}:${GITHUB_SHA}" \
            --build-arg "BASEIMAGE=${{ matrix.BASEIMAGE }}" \
            --build-arg "APPIMAGETOOL_URL=${{ matrix.APPIMAGETOOL_URL }}" \
            --build-arg "APPIMAGETOOL_SHA256=${{ matrix.APPIMAGETOOL_SHA256 }}" \
            .
      - name: push image
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${GITHUB_ACTOR}" --password-stdin
          docker tag \
            "${GITHUB_REPOSITORY}-${{ matrix.arch }}:${GITHUB_SHA}" \
            "ghcr.io/${GITHUB_REPOSITORY}-${{ matrix.arch }}:${GITHUB_REF/#refs\/tags\//}"
          docker push "ghcr.io/${GITHUB_REPOSITORY}-${{ matrix.arch }}:${GITHUB_REF/#refs\/tags\//}"
